### ISSUE TITLE
OpenDC location in keys.json file is redundant

### ISSUE THREAD

**Issue by sacheendra** [atlarge-research/opendc#11]
The location of opendc inside a container is decided in the Dockerfile. But, this location also needs to be present in the keys.json. Mismatch between these locations leads to errors. 

Make docker location in keys.json optional so that users don't need to enter it.

**Comment by gandreadis** [comment]
@sacheendra With 'docker location', are you referring to the `ROOT_DIR` field?

**Comment by sacheendra** [comment]
Yes

**Comment by leonoverweel** [comment]
IIRC the web server uses the `ROOT_DIR` field, right?

**Comment by sacheendra** [comment]
@leonoverweel I see the utility of the field for web server. I think I will overwrite whatever value is in the keys.json during image build time. So that there are no issue due to mismatch between the path in keys.json and the actual location inside the docker image. While not using docker, the field will still be considered.

**Comment by leonoverweel** [comment]
When not using docker, the server setup guide has its own specification for `keys.json`, though. So then it's probably safe to remove it from the main repository, I think.
