### ISSUE TITLE
Add CI to github

### ISSUE THREAD

**Issue by DanteNiewenhuis** [atlarge-research/opendc#176]

**Comment by DanteNiewenhuis** [comment]
Add a CI to the github that executes all test before pushing to the master is allowed

**Comment by fabianishere** [comment]
@DanteNiewenhuis This already exists in this repo, you should not be allowed to push to master unless you create a PR and the status checks pass. However, as an admin you can still override this.

**Comment by DanteNiewenhuis** [comment]
@fabianishere I have indeed seen that the CI already exists.
I have made a few small adjustments and am happy with it for now.
