### ISSUE TITLE
List dependencies in the readme

### ISSUE THREAD

**Issue by lfdversluis** [atlarge-research/opendc#2]
I see that docker is required for opendc to run, it might be useful to add all dependencies that are required to be listed in the readme.

Perhaps even an apt-get line for linux distro's and links + versions for mac/windows/etc.?

**Comment by leonoverweel** [comment]
@sacheendra can you take a look at this?

**Comment by leonoverweel** [comment]
@lfdversluis are you happy with the current `README`, or is there some other information you'd still like to see?

**Comment by lfdversluis** [comment]
Should be good now, was more of a note to you guys that it should be listed ;)

**Comment by leonoverweel** [comment]
Thanks, closing this issue.
