### ISSUE TITLE
Google login broken

### ISSUE THREAD

**Issue by lukemunn** [atlarge-research/opendc#21]
Logging into the opendc.org website using Google no longer works. 

I believe I submitted a ticket about this - which was resolved - but the ticket is now also gone. 

I have tried both Chrome and Firefox, have cleared cookies and tried again, etc. No luck. 

Be great to get this resolved. :-)

**Comment by fabianishere** [comment]
Hi @lukemunn,

There was some issue with the web server instance running [opendc.org](https://opendc.org). I have tried to resolve the issue.

Could you verify whether it works for you again?

**Comment by lukemunn** [comment]
Yes logging in now works. Thanks for resolving.
