### ISSUE TITLE
Higher granularity in export rate

### ISSUE THREAD

**Issue by Radu-Nicolae** [atlarge-research/opendc#270]
Continuation of #268. Currently, you cannot set an export rate / monitoring time of less than 1 second. The current used atomic value is `long`, linked with duration in seconds.

Suggested solution, with change in `ScenarioRunner`: 
<img width="1353" alt="Screenshot 2024-11-17 at 7 01 06 PM" src="https://github.com/user-attachments/assets/888ddcaa-7cf5-491d-99d3-236ab5fa2c89">

This would allow a higher granularity by selecting the monitoring intervals in milliseconds instead of seconds.

**Comment by DanteNiewenhuis** [comment]
Please provide an example of an experiment where we need to have sub-second export rate.

I have not yet been able to think of one.
