### ISSUE TITLE
Sidebars hide zoom buttons, export buttons and scale

### ISSUE THREAD

**Issue by linuswagner** [atlarge-research/opendc#41]
When extended, both sidebars hide the content below them.  
This includes the zoom and export buttons on the left and the scale indicator on the right (see images).

I would expect the elements to move towards the middle of the screen when the sidebars are extended

| ![image](https://user-images.githubusercontent.com/30393823/140727903-f9d87c61-bf8e-4bea-82e2-e1bf3e424437.png) | 
|:--:| 
| *Sidebars extended, buttons hidden by them* |

| ![image](https://user-images.githubusercontent.com/30393823/140727960-3bd126f3-2f6f-4b0f-a7c4-a73b6803b887.png) | 
|:--:| 
| *Sidebars collapsed, buttons visible in lower corners* |

**Comment by fabianishere** [comment]
Hi Linus, 

Thank you for reporting this issue. 🙂 
This is a known issue of the current web interface. There is fortunately already a fix for this issue in the master branch, which should be available when OpenDC v2.1 is released.

I will keep the issue open for now, so others can also see it.
